### ISSUE TITLE
Fill up the section Acknowledgements

### ISSUE THREAD

**Issue by mtitov** [ATLAS-Titan/allocation-modeling-paper#1]

**Comment by mtitov** [comment]
example of acknowledging we had used for our poster at CHEP2018:
> This research used resources of the Oak Ridge Leadership Computing Facility at the Oak Ridge National Laboratory, which is supported by the Office of Science of the U.S. Department of Energy under Contract No. DE-AC05-00OR22725. We also would like to express our appreciation to the Advanced Scientific Computing Research (ASCR) Leadership Computing Challenge (ALCC) and to all involved in this project, especially to OLCF working group. This work was funded in part by the Russian Ministry of Science and Education under contract No. 14.Z50.31.0024.

**Comment by shantenujha** [comment]
I think this is a nice and adequate acknowledgement.
