### ISSUE TITLE
Section 3.1

### ISSUE THREAD

**Issue by mtitov** [ATLAS-Titan/allocation-modeling-paper#4]
Section about general description of the static strategy selection. Should the approach of dynamic resource selection (from the paper "A Lightweight Model for Right-Sizing Master-Worker Applications") be mentioned here?

**Comment by shantenujha** [comment]
I think Related work is more appropriate ... it could be both !

**Comment by mtitov** [comment]
SJ: "In Section 3, we need to begin with a cleaner distinction between static versus 
dynamic strategy."

**Comment by mtitov** [comment]
resolved
