### ISSUE TITLE
An outdated reference

### ISSUE THREAD

**Issue by mtitov** [ATLAS-Titan/allocation-modeling-paper#6]
There is an outdated reference (Titan Scheduling Policy) which is not accessible online anymore and is presented in the paper as a footnote (in sec.4.2). Just to confirm that it is acceptable to use InternetArchive url (?):

* Titan Scheduling Policy, [https://www.olcf.ornl.gov/for-users/system-user-guides/titan/titan-user-guide/#titan-scheduling-policy](https://www.olcf.ornl.gov/for-users/system-user-guides/titan/titan-user-guide/#titan-scheduling-policy) [accessed on 2019-04-15] _Internet Archive_ [http://web.archive.org/web/20190219213055/https://www.olcf.ornl.gov/for-users/system-user-guides/titan/titan-user-guide/#titan-scheduling-policy](http://web.archive.org/web/20190219213055/https://www.olcf.ornl.gov/for-users/system-user-guides/titan/titan-user-guide/#titan-scheduling-policy)

**Comment by shantenujha** [comment]
Normally, web.archive.org would be ok, but I tried to access the site and it failed to render the page, even after 15+ seconds. We should probably take a snapshot of the policy and upload to the github pages associated with the paper. OK?

**Comment by shantenujha** [comment]
https://github.com/ATLAS-Titan/allocation-modeling/tree/master/titan-policy

**Comment by mtitov** [comment]
yeah, that's a good solution, updated accordingly
